# Используем базовый образ Node.js
FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/

RUN npm ci --omit=dev --ignore-scripts

COPY . .

CMD ["npm", "run", "prisma:migrate"]