services:
  user_db:
    image: postgres:latest
    container_name: user_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    restart: unless-stopped
    ports:
      - "4000:4000"
    depends_on:
      - user_db
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
